package Errorcode


const (
	OK = 0
	PARAMS_WRONG = -1
	NOT_EXIST = -2
	DB_OPERATE_WRONG = -3
	LOGIN_FAILED = -4
	CACHE_PROBLEM = -5
	CACHE_KEY_NOT_EXIST = -6
	PARAMS_VALIDATE_WRONG = -7
	CONNECT_GRPC_FAILED = -8
)
